hostname = "http.sandbox.drogue.cloud"   # Replace with your own Drogue Cloud instance if you are not using the sandbox
port = "443"
wifi-ssid = "..."                        # The WiFi network SSID
wifi-password = "..."                    # The WiFi network pre-shared key
http-username = "device1@wifi-workshop"  # The device username (I.e. `device1@wifi-workshop`)
http-password = "mysecretpassword"       # The device password (I.e. `mysecretpassword`)
