= From WiFi to Websocket

This workshop focuses on the use case of reporting data from an embedded device, to the cloud, receive telemetry data in a web application, and send commands back to the device.

The idea is that you have some embedded device, with a WiFi modem, reporting data to the cloud, and occasionally receiving back commands to control the device.

== Pre-requisites

This workshop requires additional hardware, as we need an embedded device with a WiFi modem.

Additionally to the common pre-requisites, you will need:

* A Drogue Device supported development board and WiFi modem
* A WiFi network
* A publicly accessible Drogue IoT Cloud instance running version 0.5+
* Standard development tools: Git

=== Supported embedded device & WiFi modem

You need a board with a supported WiFi adapter such as the https://www.st.com/en/evaluation-tools/b-l475e-iot01a.html[STM32L4 Discovery Kit]. You may also use a different Drogue Device supported board. However, this means
that you need to adapt the provided example firmware yourself.

=== Drogue Cloud

For this workshop, we recommend using the https://sandbox.drogue.cloud[Drogue Cloud Sandbox].