hostname = "http.sandbox.drogue.cloud"   # Replace with your own Drogue Cloud instance if you are not using the sandbox
#hostname = "http-endpoint-drogue-dev.apps.wonderful.iot-playground.org"   # Uncomme
port = "443"
wifi-ssid = "spiderweb" # The WiFi network SSID
wifi-password = "rosaisen"                    # The WiFi network pre-shared key
http-username = "iot01a@dfu-workshop"  # The device username (I.e. `device1@wifi-workshop`)
http-password = "1234"       # The device password (I.e. `mysecretpassword`)

led = "blue"
