[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run"

rustflags = [
    # Code-size optimizations.
    "-Z", "trap-unreachable=no",
    "-C", "inline-threshold=5",
    "-C", "no-vectorize-loops",
]

[build]
target = "thumbv7em-none-eabihf"
