name: Build

on:
  push:
    branches: [staging, trying, main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build examples
        run: for i in wifi-websockets-workshop; do pushd examples/$i; cargo build --release; popd; done;
